OnlineStore/Models/Cart.cs
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;

namespace OnlineStore.Models
{
    public class Cart
    {
        private OnlineStoreContext _context;
        private Cart(OnlineStoreContext context)
        {
            _context = context;
        }

        public string CartId { get; set; }
        public List<CartItem> CartItems { get; set; }

        public static Cart GetCart(IServiceProvider serviceProvider)
        {
            ISession session = serviceProvider.GetRequiredService<IHttpContextAccessor>()?.HttpContext.Session;

            var context = new OnlineStoreContext(serviceProvider.GetRequiredService<DbContextOptions<OnlineStoreContext>>());
            string cartId = session.GetString("CartId") ?? Guid.NewGuid().ToString();

            session.SetString("CartId", cartId);

            return new Cart(context) { CartId = cartId };
        }

        public void AddToCart(Product product, int quantity)
        {
            var cartItem = _context.CartItems.SingleOrDefault(ci => ci.Product.Id == product.Id && ci.CartId == CartId);

            if (cartItem == null)
            {
                cartItem = new CartItem
                {
                    CartId = CartId,
                    Product = product,
                    Quantity = quantity
                };

                _context.CartItems.Add(cartItem);
            } else
            {
                cartItem.Quantity++;
            }

            /** ??? For some reason, it's tracking a local change to a product and throwing a DB error for
             * trying to make an update to a DB with ID INSERT disabled. Clearing the local cache as a hacky
             * solution 'til I have time to look into the real reason it is happening. **/
            _context.Products.Local.Clear();
            _context.SaveChanges();
        }

        public int RemoveFromCart(Product product)
        {
            var cartItem = _context.CartItems.SingleOrDefault(ci => ci.Product.Id == product.Id && ci.CartId == CartId);

            var localQuantity = 0;

            if (cartItem != null)
            {
                if (cartItem.Quantity > 1 )
                {
                    cartItem.Quantity--;
                    localQuantity = cartItem.Quantity;
                } else
                {
                    _context.CartItems.Remove(cartItem);
                }
            }

            /** ??? For some reason, it's tracking a local change to a product and throwing a DB error for
             * trying to make an update to a DB with ID INSERT disabled. Clearing the local cache as a hacky
             * solution 'til I have time to look into the real reason it is happening. **/
            _context.Products.Local.Clear(); 
            _context.SaveChanges();

            return localQuantity;
        }

        public void EmptyCart()
        {
            var cartItems = _context
                .CartItems
                .Where(cart => cart.CartId == CartId);

            _context.CartItems.RemoveRange(cartItems);

            _context.SaveChanges();
        }

        public decimal GetTotalCost()
        {
            var total = _context.CartItems.Where(ci => ci.CartId == CartId)
                .Select(ci => ci.TotalPriceWithTaxes()).Sum();
            return total;
        }

        public decimal GetTotalTaxes()
        {
            var total = _context.CartItems.Where(ci => ci.CartId == CartId)
                .Select(ci => ci.TotalTaxes()).Sum();
            return total;
        }

        public List<CartItem> GetCartContents()
        {
            return CartItems ??
                   (CartItems = _context.CartItems.Where(ci => ci.CartId == CartId)
                           .Include(ci => ci.Product)
                           .ToList());
        }
    }
}

OnlineStore/Models/CartViewModel.cs
namespace OnlineStore.Models
{
    public class CartViewModel
    {
        public Cart ShoppingCart { get; set; }
        public decimal TotalPrice { get; set; }
        public decimal TotalTaxes { get; set; }
    }
}

OnlineStore/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineStore.Models;
using System.Linq;

namespace OnlineStore.Controllers
{
    public class CartController : Controller
    {
        private readonly OnlineStoreContext _context;
        private readonly Cart _shoppingCart;

        public CartController(OnlineStoreContext context, Cart shoppingCart)
        {
            _context = context;
            _shoppingCart = shoppingCart;
        }

        public ViewResult Index()
        {
            var items = _shoppingCart.GetCartContents();
            _shoppingCart.CartItems = items;

            var cartViewModel = new CartViewModel
            {
                ShoppingCart = _shoppingCart,
                TotalPrice = _shoppingCart.GetTotalCost(),
                TotalTaxes = _shoppingCart.GetTotalTaxes()
            };

            return View(cartViewModel);
        }

        public ViewResult Checkout()
        {
            var items = _shoppingCart.GetCartContents();
            _shoppingCart.CartItems = items;

            var cartViewModel = new CartViewModel
            {
                ShoppingCart = _shoppingCart,
                TotalPrice = _shoppingCart.GetTotalCost(),
                TotalTaxes = _shoppingCart.GetTotalTaxes()
            };

            return View(cartViewModel);
        }

        public RedirectToActionResult AddToCart(int productId)
        {
            var selectedProduct = _context.Products.FirstOrDefault(p => p.Id == productId);
            if (selectedProduct != null)
            {
                _shoppingCart.AddToCart(selectedProduct, 1);
            }

            return RedirectToAction("List","Products");
        }

        public RedirectToActionResult EmptyCart()
        {
            _shoppingCart.EmptyCart();

            return RedirectToAction("List", "Products");
        }

        public ViewResult ThankYou()
        {
            _shoppingCart.EmptyCart();

            return View();
        }

        public RedirectToActionResult RemoveFromCart(int productId)
        {
            var selectedProduct = _context.Products.FirstOrDefault(p => p.Id == productId);
            if (selectedProduct != null)
            {
                _shoppingCart.RemoveFromCart(selectedProduct);
            }

            return RedirectToAction("Index");
        }
    }
}

OnlineStore/Views/Cart/Checkout.cshtml
@model CartViewModel

@*This form just displays an ultra-basic summary of the cart to reflect the style of the prompt.*@
<div class="row checkoutForm">
    <h4>Cart Summary</h4>

    @if (Model.ShoppingCart.CartItems.Count > 0)
    {
        <table align="center">
            @foreach (var line in Model.ShoppingCart.CartItems)
            {
                <tr>
                    <td colspan="4" class="text-right">@line.ToString()</td>
                </tr>
            }
            <tr height="10px" background-color="#FFFFFF"></tr>
            <tr>
                <td colspan="3" class="text-right">Total Taxes:</td>
                <td class="text-right">
                    @Model.TotalTaxes.ToString("c")
                </td>
            </tr>
            <tr>
                <td colspan="3" class="text-right">Total:</td>
                <td class="text-right">
                    @Model.TotalPrice.ToString("c")
                </td>
            </tr>
        </table>
         
        <div class="text-right">
            <div class="btn-group ">
                <a class="btn btn-success" asp-controller="Cart" asp-action="ThankYou">Confirm</a>
            </div>
        </div>
    }
</div>

OnlineStore/Views/Cart/Index.cshtml
@model CartViewModel

<h3>Shopping Cart</h3>
<div class="row checkoutForm">
    @if (Model.ShoppingCart.CartItems.Count > 0)
    {
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Quantity</th>
                    <th>Product</th>
                    <th>Category</th>
                    <th class="text-right">Price per item</th>
                    <th class="text-right">Subtotal</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var line in Model.ShoppingCart.CartItems)
                {
                    <tr>
                        <td class="text-center">@line.Quantity</td>
                        <td class="text-left">@line.Product.ToString()</td>
                        <td class="text-left">@line.Product.Category</td>
                        <td class="text-right">@line.Product.Price.ToString("c")</td>
                        <td class="text-right">
                            @(line.TotalPriceWithTaxes().ToString("c"))
                        </td>
                        <td class="text-center"><a class="glyphicon glyphicon-remove text-danger remove" asp-controller="Cart" asp-action="RemoveFromCart" asp-route-productId="@line.Product.Id"></a></td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="4" class="text-right">Total Taxes:</td>
                    <td class="text-right">
                        @Model.TotalTaxes.ToString("c")
                    </td>
                </tr>
                <tr>
                    <td colspan="4" class="text-right">Total:</td>
                    <td class="text-right">
                        @Model.TotalPrice.ToString("c")
                    </td>
                </tr>
            </tfoot>
        </table>
        <div class="text-right">
            <div class="btn-group ">
                <a class="btn btn-success" asp-controller="Cart" asp-action="Checkout">Check out</a>
                <a class="btn btn-default" asp-controller="Products" asp-action="List">Continue shopping</a>
            </div>
        </div>
    }
    else
    {
        <h4>Your cart is empty.</h4>
        <div class="text-right">
            <div class="btn-group ">
                <a class="btn btn-default" asp-controller="Products" asp-action="List">Continue shopping</a>
            </div>
        </div>
    }
</div>

OnlineStore/Views/Cart/ThankYou.cshtml
<div class="row checkoutForm">
    <h1>Thank you for shopping at OnlineStore!</h1>
    <div class="text-left">
        <div class="btn-group ">
            <a class="btn btn-success" asp-controller="Home" asp-action="Index">Go Home</a>
        </div>
    </div>
</div>